name: SimpleSetSpawn
version: '${project.version}'
main: mrstreeet.simplesetspawn.SimpleSetSpawn
api-version: 1.13
authors: [ MrStreeet ]
description: A simple set spawn plugin.
website: https://github.com/MrStreeet

commands:
  simplesetspawn:
    aliases: "sss"
    permission: "simplesetspawn.admin"
    description: Main command
  setspawn:
    description: Set world spawn point.
  spawn:
    description: Teleport to the world spawn point.